##########
# Project Information

site_name: Champlain Saint-Lambert WeBWorK
site_url: https://champlainww.ca
site_description: Landing pages and documentation for WeBWorK at Champlain College Saint-Lambert
site_author: Malcolm Harper

repo_url: https://github.com/cslmath/champlainww.ca
repo_name: Site Source

# edit_uri: edit/main/docs/
edit_uri: ""

copyright: CC BY-SA &copy; 2009-2022 Champlain College Saint-Lambert WeBWorK

##########
# layout
 
nav:
    - Students:
        - students/students.md
        - Logging in: students/students-log-in.md
        - I still cannot log in: students/students-still-cannot-log-in.md
        - Doing assignments: students/students-doing-assignments.md
        - Entering answers: students/students-entering-answers.md
    - Instructors:
        - instructors/instructors.md
        - Import a classlist: instructors/ins-import-classlist.md
        - Create a homework set: instructors/ins-create-set.md
        - Math achievements: instructors\ins-math-achievements.md
        - Quizzes: instructors/ins-quiz-tips.md
        - Diagnostic quizzes: instructors/ins-diagnostic-quizzes.md
    - Authors:
        - authors/authors.md
        - Problem randomization: authors/author-randomization.md
        - Gotchas: authors/author-tips-gotchas.md
    - About:
        - about/about.md
        - News: about/about-news.md
        - WeBWorK: about/about-ww.md
        - Students quotes: about/about-quotes.md
        - This site: about/about-docs.md

##########
# Build

theme:
    # name: mkdocs
    # locale: en
    name: material
    custom_dir: overrides
    features:
        - navigation.tabs
#        - navigation.tabs.sticky
#        - navigation.sections      # incompatible with toc.integrate
#       - navigation.expand
        - navigation.top
        - navigation.indexes
#        - toc.integrate             # incompatible with navigation.sections
        - announce.dismiss          # click away the announcement bar https://squidfunk.github.io/mkdocs-material/setup/setting-up-the-header/#mark-as-read
        - search.suggest            # Experimental https://squidfunk.github.io/mkdocs-material/setup/setting-up-site-search/#search-suggestions
        - search.highlight

    palette: 
        - media: "(prefers-color-scheme: light"
 #         scheme: default
          scheme: champlain  
          toggle:
              icon: material/lightbulb-outline 
              name: Switch to dark mode
        - media: "(prefers-color-scheme: dark"
          scheme: slate 
          toggle:
              icon: material/lightbulb
              name: Switch to light mode
    logo: assets/logo.svg
    favicon: assets/favicon.svg
    icon:
        repo: fontawesome/brands/github

extra_css:
  - stylesheets/mathjax.css
  - stylesheets/banner.css
  - stylesheets/champlain.css

extra_javascript:
    - javascripts/mathjax.js
    - https://polyfill.io/v3/polyfill.min.js?features=es6
    - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

extra:
    version: 1.0.0

##########
# Preview controls

use_directory_urls: false   # true for links like /students/
                            # false for links like /students/index.html
watch:
    - overrides             # watch for updates in the overrides

##########
# Formatting options

markdown_extensions:
    - smarty
    - admonition
    - pymdownx.details      # makes admonitions collapsible
    - pymdownx.keys         # ++HMWK Sets++ etc
    - toc:
        permalink: false
        title: Table of contents
        toc_depth: 2-3
# Needed for adding atributes so that we can use LaTeX in toc entries
    - attr_list
    - pymdownx.arithmatex:
        generic: true
    - pymdownx.emoji: # for easy use of icons and emojis
        emoji_index: !!python/name:materialx.emoji.twemoji
        emoji_generator: !!python/name:materialx.emoji.to_svg
# For code highlighting
# See https://squidfunk.github.io/mkdocs-material/reference/code-blocks/
    - pymdownx.highlight:
        anchor_linenums: true
    - pymdownx.inlinehilite
    - pymdownx.snippets
    - pymdownx.superfences

plugins:
    - search:
        lang: en
            
    - git-revision-date-localized:
        type: timeago
        custom_format: "%d. %B %Y"
        timezone: Europe/Amsterdam
        locale: en
#        fallback_to_build_date: false
#        enable_creation_date: true  # leave this off until we can reset the creation date using meta (currently insiders only
        exclude:
          - index.md
        enabled: true
# Redirects
    - redirects:
        redirect_maps:
            news.md: about/about-news.md
            wwdoc/WWcannotlogin.md: students/students-still-cannot-log-in.md
            wwdoc/WWstudenttips.md: students/students.md
            wwdoc/createset.md: instructors/ins-create-set.md
            wwdoc/index.md: index.md
# Minify
    - minify:
        minify_html: false
        minify_js: true
        minify_css: true
        htmlmin_opts:
            remove_comments: true
        js_files:
            - javascripts/mathjax.js
        css_files:
            - stylesheets/mathjax.css
            - stylesheets/banner.css
            - stylesheets/champlain.css
