##########
# Project Information

site_name: Champlain Saint-Lambert WeBWorK
# site_url: https://malcolmharper.ca/
site_url: https://maharper.github.io/
site_description: Experimentation and Testing MkDocs
site_author: Malcolm Harper

repo_url: https://github.com/maharper/maharper.github.io/
repo_name: Site Source

# edit_uri: edit/main/docs/
edit_uri: ""

copyright: CC BY-SA &copy; 2009-2022 Champlain College Saint-Lambert WeBWorK

##########
# layout
 
nav:
    - Students:
        - students/students.md
        - Tips for students: students/WWstudenttips.md
        - I still can't log in: students/WWcannotlogin.md
    - Instructors:
        - instructors/instructors.md
        - Create a homework set: instructors/WWcreateset.md
#        - Import a classlist: instructors/WWimport-classlist.md
    - Authors:
        - authors/authors.md
        - MkDocs vs Pelican: authors/mkdocs-vs-pelican.md
        - MkDocs: authors/mkdocs.md
    - About:
        - about/about.md
        - News: about/about-news.md
        - WeBWorK: about/about-ww.md
        - Students' quotes: about/about-quotes.md
        - This site: about/about-docs.md

##########
# Build

theme:
    # name: mkdocs
    # locale: en
    name: material
    custom_dir: overrides
    features:
        - navigation.tabs
#        - navigation.tabs.sticky
#        - navigation.sections      # incompatible with toc.integrate
#       - navigation.expand
        - navigation.top
        - navigation.indexes
#        - toc.integrate             # incompatible with navigation.sections
        - announce.dismiss          # click away the announcement bar https://squidfunk.github.io/mkdocs-material/setup/setting-up-the-header/#mark-as-read
    palette: 
        - media: "(prefers-color-scheme: light)"
          scheme: default
          toggle:
              icon: material/lightbulb-outline 
              name: Switch to dark mode
        - media: "(prefers-color-scheme: dark)"
          scheme: slate 
          toggle:
              icon: material/lightbulb
              name: Switch to light mode
    icon:
        repo: fontawesome/brands/github

extra_css:
  - stylesheets/mathjax.css

extra_javascript:
    - javascripts/mathjax.js
    - https://polyfill.io/v3/polyfill.min.js?features=es6
    - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

extra:
    version: 0.0.1

##########
# Preview controls

use_directory_urls: false   # true for links like /students/
                            # false for links like /students/index.html
watch:
    - overrides             # watch for updates in the overrides

##########
# Formatting options

markdown_extensions:
    - smarty
    - admonition
    - pymdownx.details      # makes admonitions collapsible
    - pymdownx.keys         # ++HMWK Sets++ etc
    - toc:
        permalink: false
        title: Table of contents
        toc_depth: 2-3
# Needed for adding atributes so that we can use LaTeX in toc entries
    - attr_list
    - pymdownx.arithmatex:
        generic: true
    - pymdownx.emoji: # for easy use of icons and emojis
        emoji_index: !!python/name:materialx.emoji.twemoji
        emoji_generator: !!python/name:materialx.emoji.to_svg

plugins:
    - search:
        lang: en
            
    - git-revision-date-localized:
        type: timeago
        custom_format: "%d. %B %Y"
        timezone: Europe/Amsterdam
        locale: en
#        fallback_to_build_date: false
#        enable_creation_date: true  # leave this off until we can reset the creation date using meta (currently insiders only)
        exclude:
          - index.md
        enabled: true
        


    
